name: Backend CI/CD

on:
  push:
    branches: [ main ]   # triggers when you push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew


      - name: Build with Gradle
        run: ./gradlew clean build
        
      - name: List build output
        run: ls -l build/libs

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'brati-trust'
          environment_name: 'brati-trust-production'
          version_label: ${{ github.sha }}
          region: 'ap-south-2'
          deployment_package: build/libs/brati-trust-0.0.1-SNAPSHOT.jar